<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="RhyCiv.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Raylib-CSharp" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Model\Model.csproj" />
      <ProjectReference Include="..\RaylibUtils\RaylibUtils.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="buttons.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
		<None Update="explorer_icons.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Fonts\LiberationSerif-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Fonts\LiberationSerif-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Fonts\LiberationSans-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Fonts\OFL-1.1.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>


</Project>
